# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/97150/PycharmProjects/pythonProject/Staff/staff_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StaffMainWindow(object):
    def setupUi(self, StaffMainWindow):
        StaffMainWindow.setObjectName("StaffMainWindow")
        StaffMainWindow.resize(937, 672)
        self.centralwidget = QtWidgets.QWidget(StaffMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.welcome_lbl = QtWidgets.QLabel(self.centralwidget)
        self.welcome_lbl.setGeometry(QtCore.QRect(9, 9, 16, 16))
        self.welcome_lbl.setText("")
        self.welcome_lbl.setObjectName("welcome_lbl")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(9, 40, 889, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(157, 50, 741, 554))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.welcome_msg_lbl = QtWidgets.QLabel(self.centralwidget)
        self.welcome_msg_lbl.setGeometry(QtCore.QRect(10, 10, 881, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.welcome_msg_lbl.setFont(font)
        self.welcome_msg_lbl.setText("")
        self.welcome_msg_lbl.setObjectName("welcome_msg_lbl")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 50, 142, 251))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.manage_staff_btn = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.manage_staff_btn.setFont(font)
        self.manage_staff_btn.setObjectName("manage_staff_btn")
        self.verticalLayout.addWidget(self.manage_staff_btn)
        self.manage_books_btn = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.manage_books_btn.setFont(font)
        self.manage_books_btn.setObjectName("manage_books_btn")
        self.verticalLayout.addWidget(self.manage_books_btn)
        self.issue_book_btn = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.issue_book_btn.setFont(font)
        self.issue_book_btn.setObjectName("issue_book_btn")
        self.verticalLayout.addWidget(self.issue_book_btn)
        self.return_book_btn = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.return_book_btn.setFont(font)
        self.return_book_btn.setObjectName("return_book_btn")
        self.verticalLayout.addWidget(self.return_book_btn)
        StaffMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StaffMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 937, 22))
        self.menubar.setObjectName("menubar")
        self.menuActions = QtWidgets.QMenu(self.menubar)
        self.menuActions.setObjectName("menuActions")
        StaffMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StaffMainWindow)
        self.statusbar.setObjectName("statusbar")
        StaffMainWindow.setStatusBar(self.statusbar)
        self.actionLogout = QtWidgets.QAction(StaffMainWindow)
        self.actionLogout.setObjectName("actionLogout")
        self.actionProfile = QtWidgets.QAction(StaffMainWindow)
        self.actionProfile.setObjectName("actionProfile")
        self.menuActions.addAction(self.actionLogout)
        self.menuActions.addAction(self.actionProfile)
        self.menubar.addAction(self.menuActions.menuAction())

        self.retranslateUi(StaffMainWindow)
        QtCore.QMetaObject.connectSlotsByName(StaffMainWindow)

    def retranslateUi(self, StaffMainWindow):
        _translate = QtCore.QCoreApplication.translate
        StaffMainWindow.setWindowTitle(_translate("StaffMainWindow", "Staff Utility Tools"))
        self.manage_staff_btn.setText(_translate("StaffMainWindow", "Manage Staff Members"))
        self.manage_books_btn.setText(_translate("StaffMainWindow", "Manage Books"))
        self.issue_book_btn.setText(_translate("StaffMainWindow", "Issue a Book"))
        self.return_book_btn.setText(_translate("StaffMainWindow", "Return a Book"))
        self.menuActions.setTitle(_translate("StaffMainWindow", "Actions"))
        self.actionLogout.setText(_translate("StaffMainWindow", "Log Out"))
        self.actionProfile.setText(_translate("StaffMainWindow", "Profile"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StaffMainWindow = QtWidgets.QMainWindow()
    ui = Ui_StaffMainWindow()
    ui.setupUi(StaffMainWindow)
    StaffMainWindow.show()
    sys.exit(app.exec_())
