# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/97150/PycharmProjects/LibraryManagement/Book/issue_book.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IssueBook(object):
    def setupUi(self, IssueBook):
        IssueBook.setObjectName("IssueBook")
        IssueBook.resize(803, 621)
        self.title_lbl = QtWidgets.QLabel(IssueBook)
        self.title_lbl.setGeometry(QtCore.QRect(70, 70, 131, 31))
        self.title_lbl.setObjectName("title_lbl")
        self.title_lineEdit = QtWidgets.QLineEdit(IssueBook)
        self.title_lineEdit.setGeometry(QtCore.QRect(240, 70, 481, 31))
        self.title_lineEdit.setObjectName("title_lineEdit")
        self.formLayoutWidget = QtWidgets.QWidget(IssueBook)
        self.formLayoutWidget.setGeometry(QtCore.QRect(220, 160, 381, 131))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(12)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.fname_lbl = QtWidgets.QLabel(self.formLayoutWidget)
        self.fname_lbl.setObjectName("fname_lbl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.fname_lbl)
        self.fname_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fname_lineEdit.setObjectName("fname_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fname_lineEdit)
        self.lname_lbl = QtWidgets.QLabel(self.formLayoutWidget)
        self.lname_lbl.setObjectName("lname_lbl")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lname_lbl)
        self.lname_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lname_lineEdit.setObjectName("lname_lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lname_lineEdit)
        self.mobno_lbl = QtWidgets.QLabel(self.formLayoutWidget)
        self.mobno_lbl.setObjectName("mobno_lbl")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.mobno_lbl)
        self.mobno_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mobno_lineEdit.setObjectName("mobno_lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.mobno_lineEdit)
        self.email_lbl = QtWidgets.QLabel(self.formLayoutWidget)
        self.email_lbl.setObjectName("email_lbl")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.email_lbl)
        self.email_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.email_lineEdit.setObjectName("email_lineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.email_lineEdit)
        self.issue_btn = QtWidgets.QPushButton(IssueBook)
        self.issue_btn.setGeometry(QtCore.QRect(290, 320, 241, 31))
        self.issue_btn.setObjectName("issue_btn")
        self.issue_msg_lbl = QtWidgets.QLabel(IssueBook)
        self.issue_msg_lbl.setGeometry(QtCore.QRect(180, 380, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.issue_msg_lbl.setFont(font)
        self.issue_msg_lbl.setText("")
        self.issue_msg_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.issue_msg_lbl.setObjectName("issue_msg_lbl")
        self.horizontalLayoutWidget = QtWidgets.QWidget(IssueBook)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(170, 440, 491, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.retranslateUi(IssueBook)
        QtCore.QMetaObject.connectSlotsByName(IssueBook)

    def retranslateUi(self, IssueBook):
        _translate = QtCore.QCoreApplication.translate
        IssueBook.setWindowTitle(_translate("IssueBook", "Issue Book"))
        self.title_lbl.setText(_translate("IssueBook", "Book Title: "))
        self.fname_lbl.setText(_translate("IssueBook", "Borrower First Name: "))
        self.lname_lbl.setText(_translate("IssueBook", "Borrower Last Name: "))
        self.mobno_lbl.setText(_translate("IssueBook", "Borrower Mobile Number: "))
        self.mobno_lineEdit.setText(_translate("IssueBook", "0"))
        self.email_lbl.setText(_translate("IssueBook", "Borrower Email: "))
        self.issue_btn.setText(_translate("IssueBook", "Issue Book"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IssueBook = QtWidgets.QWidget()
    ui = Ui_IssueBook()
    ui.setupUi(IssueBook)
    IssueBook.show()
    sys.exit(app.exec_())
